### ISSUE TITLE
Roblox and Captchas with groups

### ISSUE THREAD

**Issue by PurityWasHere** [KristanSmout/RobloxPyOfficial#1]
Roblox started using captchas when joining groups if the cookies / headers are improper. Also if they detect a proxy sometimes.

I made a change to the code to notify if a captcha check was returned.

`def JoinGroup(Cookie, GroupID, Proxy=None):
    SetProxy(Proxy)
    try:
        session = SetCookie(Cookie,Proxy)
        Post = session.post(GroupAPIV1 + str(GroupID) + '/users')
        if 'captcha test' in Post.content.decode():
            return 'Captcha'
        else:
            return 'Joined'
    except:
        return 'Error: ', CheckCookie(Cookie)`

**Comment by KristanSmout** [comment]
Thanks this will be added to the 0.2.1 release.
