### ISSUE TITLE
There seems to be an issue with GetLimitedChangePercentage

### ISSUE THREAD

**Issue by DO-Ui** [KristanSmout/RobloxPyOfficial#10]
When I try and use this it keeps giving me a TypeError saying "unsupported operand type(s) for -: 'float' and 'NoneType'"

Not sure what causes it but its just something I encountered

**Comment by anytarseir67** [comment]
can't reproduce, what did you pass in?

**Comment by DO-Ui** [comment]
I put in the ID for https://www.roblox.com/catalog/1016143686/White-Sparkle-Time-Fedora

**Comment by DO-Ui** [comment]
my full code was 
```
import robloxpy.Market.External
print(robloxpy.Market.External.GetLimitedChangePercentage(1016143686))
```

**Comment by DO-Ui** [comment]
All other commands seem to work except this one

**Comment by DO-Ui** [comment]
![image](https://user-images.githubusercontent.com/68296986/129742127-0686e7ec-1ba3-4e0b-a12a-3b4b18fb143c.png)

**Comment by anytarseir67** [comment]
as far as i can tell this isn't an issue with the lib. the api can return None for the sale price. not entirely sure why though, since the docs for the economy api have been removed.

**Comment by DO-Ui** [comment]
That's odd but I suppose not a bug
