### ISSUE TITLE
Player Busts returning 404 not found

### ISSUE THREAD

**Issue by DO-Ui** [KristanSmout/RobloxPyOfficial#19]
When I use `robloxpy.User.External.GetBust([roblox user id])` it returns a link that when visited with a browser shows the Roblox 404 page.
Example returned url: https://www.roblox.com/bust-thumbnail/image?userId=1017316928&width=420&height=420&format=png

**Comment by anytarseir67** [comment]
i'd advise you use a different library, this one is quite dead at this point

**Comment by DO-Ui** [comment]
🫠 Alright thanks for the advice.
