### ISSUE TITLE
robloxpy has no module '...'

### ISSUE THREAD

**Issue by wchalexander** [KristanSmout/RobloxPyOfficial#4]
Hello, I tried using the robloxpy module with VSC and Python IDE but none of the attributes work.  It says "module 'robloxpy' has no attribute 'Game'" or "module 'robloxpy' has no attribute 'Market'". Could you heal me please.

**Comment by anytarseir67** [comment]
if you still want to use this lib, you can try this pr #5

**Comment by KristanSmout** [comment]
#5 was merged so this should no longer be an issue.
